### ISSUE TITLE
More DAta

### ISSUE THREAD

**Issue by moelfassi** [ophobe/trending-youtube#1]
Hi I need more data, if you have any please share them.
or if you can help please see this 
[https://stackoverflow.com/questions/47127792/get-youtube-old-trending-videos 
](url)
Thank you!

**Comment by ecrmnn** [comment]
This is all the data that I've got. 
I'd love to see what you're working on. Please link!

**Comment by moelfassi** [comment]
Hi sorry for being late.. i'm using this for my youtube channel to study how videos got trending..
i think the engagement factor is important.. specially commenting on a video

**Comment by moelfassi** [comment]
Thank for the effort
